mongo:
  host: localhost
  port: 27017
  database: contentapi
  username: dev
  password: dev

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/sso/user

server:
  port: 9000
  contextPath: /content-api-server

---

mongo:
  host: mongodb
  port: 27017
  database: contentapi
  username: dev
  password: dev

spring:
  profiles: production
  oauth2:
    resource:
      userInfoUri: http://oauth2-server:8080/sso/user

server:
  port: 8080
  contextPath: /content-api-server