mongo:
  host: localhost
  port: 27017
  database: contentapi
  username: dev
  password: dev

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9080/sso/user

server:
  port: 8080
  contextPath: /contentapi