mongo:
  host: localhost
  port: 27017
  database: copyshare
  username: dev
  password: dev

spring:
  oauth2:
    resource:
      userInfoUri: http://127.0.0.1:9080/sso/user

info:
  app:
    name: contentapi
    description: Content API Rest Service

server:
  port: 8080
  contextPath: /contentapi
